// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwNIIhMu5ZqpeghXs4Zg9yz4YJEFUsS8s',
    appId: '1:700947391250:web:da004d9a70998b11ae89cb',
    messagingSenderId: '700947391250',
    projectId: 'memeverse-2bc9f',
    authDomain: 'memeverse-2bc9f.firebaseapp.com',
    storageBucket: 'memeverse-2bc9f.firebasestorage.app',
    measurementId: 'G-ZJJC254E79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMIz9uuNGHMRU8iQ_ATfiQ5c8XELuvHjk',
    appId: '1:700947391250:android:d7c0e8eb8e81543bae89cb',
    messagingSenderId: '700947391250',
    projectId: 'memeverse-2bc9f',
    storageBucket: 'memeverse-2bc9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Sb4dXCOEWcxxOKepeoJSU28de5nrMfw',
    appId: '1:700947391250:ios:68635b7d20fb69c6ae89cb',
    messagingSenderId: '700947391250',
    projectId: 'memeverse-2bc9f',
    storageBucket: 'memeverse-2bc9f.firebasestorage.app',
    iosBundleId: 'com.example.memeVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Sb4dXCOEWcxxOKepeoJSU28de5nrMfw',
    appId: '1:700947391250:ios:68635b7d20fb69c6ae89cb',
    messagingSenderId: '700947391250',
    projectId: 'memeverse-2bc9f',
    storageBucket: 'memeverse-2bc9f.firebasestorage.app',
    iosBundleId: 'com.example.memeVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwNIIhMu5ZqpeghXs4Zg9yz4YJEFUsS8s',
    appId: '1:700947391250:web:2b543cdf59d03d17ae89cb',
    messagingSenderId: '700947391250',
    projectId: 'memeverse-2bc9f',
    authDomain: 'memeverse-2bc9f.firebaseapp.com',
    storageBucket: 'memeverse-2bc9f.firebasestorage.app',
    measurementId: 'G-QQ23RS65KG',
  );
}
