part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LOGIN = _Paths.LOGIN;
  static const SPLASH = _Paths.SPLASH;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const SSP = _Paths.SSP;
  static const MY_REQUISITION = _Paths.MY_REQUISITION;
  static const MY_APPROVAL = _Paths.MY_APPROVAL;
  static const PHONEBOOK = _Paths.PHONEBOOK;
  static const PROFILE = _Paths.PROFILE;
  static const TNA = _Paths.TNA;
  static const MNM = _Paths.MNM;
  static const MNM_INQUERY = _Paths.MNM_INQUERY;
  static const PRICE_QUOTATION = _Paths.PRICE_QUOTATION;
  static const MNM_ENQUERY_STATUS = _Paths.MNM_ENQUERY_STATUS;
  static const TNA_TRAFFIC = _Paths.TNA_TRAFFIC;
  static const ATTENDANCE_REQUISITION = _Paths.ATTENDANCE_REQUISITION;
  static const LEAVE_REQUISITION = _Paths.LEAVE_REQUISITION;
  static const GENERAL_STORE_REQUISITION = _Paths.GENERAL_STORE_REQUISITION;
  static const ICT_STORE_REQUISITION = _Paths.ICT_STORE_REQUISITION;
  static const ICT_SERVICE_REQUISITION = _Paths.ICT_SERVICE_REQUISITION;
  static const API_CONFIG = _Paths.API_CONFIG;
  static const FILE_PREVIEW = _Paths.FILE_PREVIEW;
  static const ATTENDANCE_SUBMISSION = _Paths.ATTENDANCE_SUBMISSION;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const NEW_REQUISITION = _Paths.NEW_REQUISITION;
  static const SSP_APPROVAL_DETAILS = _Paths.SSP_APPROVAL_DETAILS;
  static const HRIS = _Paths.HRIS;
  static const PROFILE_PIC_AND_SIGNATURE = _Paths.PROFILE_PIC_AND_SIGNATURE;
  static const MY_REQUISITION_DETAILS = _Paths.MY_REQUISITION_DETAILS;
  static const ATTENDANCE = _Paths.ATTENDANCE;
  static const COMPANY = _Paths.COMPANY;
  static const EMPLOYEE_BUDGET = _Paths.EMPLOYEE_BUDGET;
  static const TEST_THEME = _Paths.TEST_THEME;
  static const TEST_TEXT_THEME = _Paths.TEST_TEXT_THEME;
  static const TEST_BUTTON_THEME = _Paths.TEST_BUTTON_THEME;
  static const TEST_INPUT_THEME = _Paths.TEST_INPUT_THEME;
  static const TEST_SNACKBAR_THEME = _Paths.TEST_SNACKBAR_THEME;
  static const TEST_DATETIME_THEME = _Paths.TEST_DATETIME_THEME;
  static const TEST_CARD_THEME = _Paths.TEST_CARD_THEME;
  static const TEST_TABBAR_THEME = _Paths.TEST_TABBAR_THEME;
  static const TEST_CHECKBOX_THEME = _Paths.TEST_CHECKBOX_THEME;
  static const TEST_POPUP_THEME = _Paths.TEST_POPUP_THEME;
  static const TEST_BOTTOMSHEET_THEME = _Paths.TEST_BOTTOMSHEET_THEME;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const SPLASH = '/splash';
  static const NOTIFICATION = '/notification';
  static const SSP = '/ssp';
  static const MY_REQUISITION = '/my-requisition';
  static const MY_APPROVAL = '/my-approval';
  static const PHONEBOOK = '/phonebook';
  static const TNA = '/tna';
  static const MNM = '/mnm';
  static const MNM_INQUERY = '/mnm-inquery';
  static const MNM_ENQUERY_STATUS = '/mnm-enquery-status';
  static const TNA_TRAFFIC = '/tna-traffic';
  static const PRICE_QUOTATION = '/price-quotation';
  static const PROFILE = '/profile';
  static const ATTENDANCE_REQUISITION = '/attendance-requisition';
  static const LEAVE_REQUISITION = '/leave-requisition';
  static const GENERAL_STORE_REQUISITION = '/general-store-requisition';
  static const ICT_STORE_REQUISITION = '/ict-store-requisition';
  static const ICT_SERVICE_REQUISITION = '/ict-service-requisition';
  static const API_CONFIG = '/api-config';
  static const FILE_PREVIEW = '/file-preview';
  static const ATTENDANCE_SUBMISSION = '/attendance-submission';
  static const CHANGE_PASSWORD = '/change-password';
  static const NEW_REQUISITION = '/new-requisition';
  static const SSP_APPROVAL_DETAILS = '/ssp-approval-details';
  static const HRIS = '/hris';
  static const PROFILE_PIC_AND_SIGNATURE = '/profile-pic-and-signature';
  static const MY_REQUISITION_DETAILS = '/my-requisition-details';
  static const ATTENDANCE = '/attendance';
  static const COMPANY = '/company';
  static const EMPLOYEE_BUDGET = '/employee-budget';
  static const TEST_THEME = '/test-theme';
  static const TEST_TEXT_THEME = '/test-text-theme';
  static const TEST_BUTTON_THEME = '/test-button-theme';
  static const TEST_INPUT_THEME = '/test-input-theme';
  static const TEST_SNACKBAR_THEME = '/test-snackbar-theme';
  static const TEST_DATETIME_THEME = '/test-datetime-theme';
  static const TEST_CARD_THEME = '/test-card-theme';
  static const TEST_TABBAR_THEME = '/test-tabbar-theme';
  static const TEST_CHECKBOX_THEME = '/test-checkbox-theme';
  static const TEST_POPUP_THEME = '/test-popup-theme';
  static const TEST_BOTTOMSHEET_THEME = '/test-bottomsheet-theme';
}
